#!/bin/sh

# .gtk_bookmarks
printf "file:///home/ghostbsd/Documents Documents
file:///home/ghostbsd/Downloads Downloads
file:///home/ghostbsd/Movies Movies
file:///home/ghostbsd/Music Music
file:///home/ghostbsd/Pictures Pictures
" > /home/ghostbsd/.gtk-bookmarks

mkdir -p /home/ghostbsd/Documents
mkdir -p /home/ghostbsd/Downloads
mkdir -p /home/ghostbsd/Movies 
mkdir -p /home/ghostbsd/Music
mkdir -p /home/ghostbsd/Pictures

mkdir -p /home/ghostbsd/Desktop

if [ -e /usr/local/share/applications/ghostbsd-irc.desktop ] ; then
    cp -af /usr/local/share/applications/ghostbsd-irc.desktop \
    /home/ghostbsd/Desktop
    chmod +x /home/ghostbsd/Desktop/ghostbsd-irc.desktop
fi

if [ -e /usr/local/share/applications/gbi.desktop ] ; then
    cp -af /usr/local/share/applications/gbi.desktop \
    /home/ghostbsd/Desktop
    chmod +x /home/ghostbsd/Desktop/gbi.desktop
fi
