#!/bin/sh
#
# $GhostBSD$
# $Id: uzip,v 1.4 Saturday, June 20 2015 12:18 Angelescu Ovidiu Exp $
#

# PROVIDE: gbsdcheats
# BEFORE: growfs
# KEYWORD: nojail

. /etc/rc.subr

name="cheatcodes"
start_cmd="cheatcodes_start"
stop_cmd="cheatcodes_stop"

cheatcodes_start() {
echo "cheatcodes start"
# Check if we are in virtualbox to enable vbox-guest-additions in rc.conf
pciconf -lv | grep -q "VirtualBox Graphics"
if  [ $? -eq 0 ] ; then
    sed -i '' -e 's/vboxguest_enable="NO"/vboxguest_enable="YES"/g' \
               -e 's/vboxservice_enable="NO"/vboxservice_enable="YES"/g' \
                /etc/rc.conf
/usr/local/etc/rc.d/vboxguest start
/usr/local/etc/rc.d/vboxservice start
fi
# Single user boot stuff
kenv boot_single > /dev/null 2>&1
if [ $? -eq 0 ] ; then
   echo "Starting emergency shell."
   echo "Type exit to resume boot"
    PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
    HOME=/root
    TERM=${TERM:-xterm}
    export TERM
    /bin/sh
fi
}

cheatcodes_stop() {
 echo "cheatcodes stop"
}

load_rc_config $name
run_rc_command "$1"
